# Generated by Django 4.2.19 on 2025-03-01 09:51

import cord4_task.product.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Selling price')),
                ('description', models.TextField(verbose_name='Description')),
                ('stock_quantity', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Quantity available')),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to=cord4_task.product.models.get_product_photo_path, width_field='width')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
